[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
parser-core = { path = "parser-core" }
parser-lang = { path = "parser-lang" }

[workspace]
members = [
    "parser-core",
    "parser-lang",
]
