[package]
name = "parser-lang"
version = "0.1.0"
edition = "2024"

[lib]

[dependencies]
phf = { version = "0.12", features = ["macros"] }
strum = { version = "0.27", features = ["derive"] }

parser-core = { path = "../parser-core" }
